// <auto-generated />
using System;
using Dotar.Gateway.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotar.Gateway.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    [Migration("20260322134627_AddTenantGroups")]
    partial class AddTenantGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DeliveryLogId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManual")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryLogId");

                    b.ToTable("DeliveryAttempts");
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.DeliveryLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WebhookEventId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NextRetryAt");

                    b.HasIndex("Status");

                    b.HasIndex("WebhookEventId");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("DeliveryLogs");
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.RetryPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CircuitBreakerDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CircuitBreakerThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RetryPolicies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CircuitBreakerDurationSeconds = 30,
                            CircuitBreakerThreshold = 5,
                            CreatedAt = new DateTime(2026, 3, 22, 13, 46, 26, 126, DateTimeKind.Utc).AddTicks(715),
                            IsDefault = true,
                            Name = "Estándar"
                        });
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.RetryStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DelayUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("DelayValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryPolicyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RetryPolicyId", "StepNumber")
                        .IsUnique();

                    b.ToTable("RetrySteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DelayUnit = "Seconds",
                            DelayValue = 5,
                            RetryPolicyId = 1,
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            DelayUnit = "Seconds",
                            DelayValue = 30,
                            RetryPolicyId = 1,
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            DelayUnit = "Minutes",
                            DelayValue = 2,
                            RetryPolicyId = 1,
                            StepNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            DelayUnit = "Minutes",
                            DelayValue = 15,
                            RetryPolicyId = 1,
                            StepNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            DelayUnit = "Hours",
                            DelayValue = 1,
                            RetryPolicyId = 1,
                            StepNumber = 5
                        });
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RetryPolicyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TenantGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookSecret")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RetryPolicyId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TenantGroupId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.TenantGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RetryPolicyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RetryPolicyId");

                    b.ToTable("TenantGroups");
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.HasOne("Dotar.Gateway.Domain.Entities.DeliveryLog", "DeliveryLog")
                        .WithMany("Attempts")
                        .HasForeignKey("DeliveryLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryLog");
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.DeliveryLog", b =>
                {
                    b.HasOne("Dotar.Gateway.Domain.Entities.Tenant", "Tenant")
                        .WithMany("DeliveryLogs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.RetryStep", b =>
                {
                    b.HasOne("Dotar.Gateway.Domain.Entities.RetryPolicy", "RetryPolicy")
                        .WithMany("Steps")
                        .HasForeignKey("RetryPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetryPolicy");
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.Tenant", b =>
                {
                    b.HasOne("Dotar.Gateway.Domain.Entities.RetryPolicy", "RetryPolicy")
                        .WithMany("Tenants")
                        .HasForeignKey("RetryPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dotar.Gateway.Domain.Entities.TenantGroup", "TenantGroup")
                        .WithMany("Tenants")
                        .HasForeignKey("TenantGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RetryPolicy");

                    b.Navigation("TenantGroup");
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.TenantGroup", b =>
                {
                    b.HasOne("Dotar.Gateway.Domain.Entities.RetryPolicy", "RetryPolicy")
                        .WithMany()
                        .HasForeignKey("RetryPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RetryPolicy");
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.DeliveryLog", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.RetryPolicy", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("DeliveryLogs");
                });

            modelBuilder.Entity("Dotar.Gateway.Domain.Entities.TenantGroup", b =>
                {
                    b.Navigation("Tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
